/*
 * CHAOS user hooks for STM32F103 (Blue Pill)
 * Generated by CHAOS Configuration Wizard
 */

#ifndef CHAOS_HOOKS_H
#define CHAOS_HOOKS_H

#include <stdint.h>
#include "os.h"

void User_StartupHook(void);
void User_ShutdownHook(void);

#endif /* CHAOS_HOOKS_H */
