/*
 * CHAOS demo tasks
 * Generated by CHAOS Configuration Wizard
 */

#include "os.h"
#include "os_task.h"
#include "strings.h"
#include "main.h"
#include "ssd1306.h"


/* Imported globals */
extern CAN_HandleTypeDef hcan;
extern TIM_HandleTypeDef htim2;
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart3;
extern ADC_HandleTypeDef hadc1;

extern ssd1306_t oled;

CAN_TxHeaderTypeDef txHeader;
uint32_t txMailbox;
uint8_t txData[8];

uint32_t adc_in1;
uint32_t adc_in2;

float temperature_c;
float voltage;


void CAN_SendMessage(uint32_t ID, uint8_t DLC, uint8_t * Data)
{
	/* Configura header */
	txHeader.StdId = ID;          		// ID standard (11 bit)
	txHeader.ExtId = 0;              	// Non usato se IDE = STD
	txHeader.IDE   = CAN_ID_STD;     	// CAN_ID_STD oppure CAN_ID_EXT
	txHeader.RTR   = CAN_RTR_DATA;   	// CAN_RTR_DATA o CAN_RTR_REMOTE
	txHeader.DLC   = DLC;              	// Numero byte (0..8)
	txHeader.TransmitGlobalTime = DISABLE;

	/* Dati */
	txData[0] = Data[0];
	txData[1] = Data[1];
	txData[2] = Data[2];
	txData[3] = Data[3];
	txData[4] = Data[4];
	txData[5] = Data[5];
	txData[6] = Data[6];
	txData[7] = Data[7];

	/* Attendi mailbox libera */
	while (HAL_CAN_GetTxMailboxesFreeLevel(&hcan) == 0);

	/* Trasmetti */
	if (HAL_CAN_AddTxMessage(&hcan, &txHeader, txData, &txMailbox) != HAL_OK)
	{
	    // ERRORE TX
	}
}

void uart3_send_string(const char *str)
{
    HAL_UART_Transmit(
        &huart3,
        (uint8_t *)str,
        strlen(str),
        HAL_MAX_DELAY
    );
}

void uart1_send_string(const char *str)
{
    HAL_UART_Transmit(
        &huart1,
        (uint8_t *)str,
        strlen(str),
        HAL_MAX_DELAY
    );
}


//#define USB_LOGGING

TASK(CAN_Task)
{
#ifdef USB_LOGGING
	printf("Task CAN_Task running...\r\n");
#endif

	static uint32_t counter = 0;
	static CAN_RxHeaderTypeDef rxHeader;
	static uint8_t rxData[8];

	uint8_t CanMsg_1[8] = {0, 0, 0, 0, 0, 0, 0xAA, 0xBB};
	uint8_t CanMsg_2[8] = {0, 0, 0, 0, 0, 0, 0, 0};

	/* Can msg 1 */
	counter++;
	CanMsg_1[0] = counter >> 24;
	CanMsg_1[1] = counter >> 16;
	CanMsg_1[2] = counter >> 8;
	CanMsg_1[3] = counter;

	CanMsg_2[0] = adc_in1 >> 8;
	CanMsg_2[1] = adc_in1;
	CanMsg_2[2] = adc_in2 >> 8;
	CanMsg_2[3] = adc_in2;

	CAN_SendMessage(0x123, 8, CanMsg_1);
	CAN_SendMessage(0x456, 8, CanMsg_2);

	/* CAN Rx */
	if (HAL_CAN_GetRxFifoFillLevel(&hcan, CAN_RX_FIFO0) > 0)
	{
	    if (HAL_CAN_GetRxMessage(&hcan, CAN_RX_FIFO0, &rxHeader, rxData) == HAL_OK)
	    {
	        // rxHeader.StdId  -> ID (se standard)
	        // rxHeader.ExtId  -> ID (se extended)
	        // rxHeader.DLC    -> numero byte validi
	        // rxData[]        -> payload
	    	if (rxHeader.StdId == 0x100)
	    	{
	    		if ((rxData[0] == 0) || (rxData[0] == 1))
	    			HAL_GPIO_WritePin(LED_1_GPIO_Port, LED_1_Pin, rxData[0]);
	    		else
	    			HAL_GPIO_TogglePin(LED_1_GPIO_Port, LED_1_Pin);
		    	HAL_GPIO_WritePin(LED_2_GPIO_Port, LED_2_Pin, rxData[1]);
		    	HAL_GPIO_WritePin(LED_3_GPIO_Port, LED_3_Pin, rxData[2]);
		    	if ((rxData[3] == 0) || (rxData[3] == 1))
		    		HAL_GPIO_WritePin(BUZZ_GPIO_Port, BUZZ_Pin, rxData[3]);
	    		else
	    			HAL_GPIO_TogglePin(BUZZ_GPIO_Port, BUZZ_Pin);
	    	}
	    }
	}


	/* Task Termination */
	Os_TerminateTask();
}

TASK(RS485_Task)
{
#ifdef USB_LOGGING
	printf("Task RS485_Task running...\r\n");
#endif

	/* TODO: User code */
	HAL_GPIO_WritePin(RS485_DE_GPIO_Port, RS485_DE_Pin, 1);
	uart1_send_string("RS485 Hello World!!!\r\n");
	HAL_GPIO_WritePin(RS485_DE_GPIO_Port, RS485_DE_Pin, 0);

	/* Task Termination */
	Os_TerminateTask();
}

TASK(LED_Task)
{
#ifdef USB_LOGGING
	printf("Task LED_Task running...\r\n");
#endif

	/* TODO: User code */
	HAL_GPIO_TogglePin(LED_0_GPIO_Port, LED_0_Pin);
	HAL_Delay(10);
	HAL_GPIO_TogglePin(LED_0_GPIO_Port, LED_0_Pin);

	/* Task Termination */
	Os_TerminateTask();
}

TASK(Readings_Task)
{
#ifdef USB_LOGGING
	printf("Task Readings_Task running...\r\n");
#endif

	ADC_ChannelConfTypeDef sConfig = {0};

	/* IN1 */
	sConfig.Channel = ADC_CHANNEL_1;          // IN1 = PA1
	sConfig.Rank = ADC_REGULAR_RANK_1;
	sConfig.SamplingTime = ADC_SAMPLETIME_28CYCLES_5;
	HAL_ADC_ConfigChannel(&hadc1, &sConfig);

	HAL_ADC_Start(&hadc1);
	HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
	adc_in1 = HAL_ADC_GetValue(&hadc1);
	HAL_ADC_Stop(&hadc1);

	/* IN2 */
	sConfig.Channel = ADC_CHANNEL_2;          // IN2 = PA2
	sConfig.Rank = ADC_REGULAR_RANK_1;        // sempre rank 1 perché scan è OFF
	HAL_ADC_ConfigChannel(&hadc1, &sConfig);

	HAL_ADC_Start(&hadc1);
	HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
	adc_in2 = HAL_ADC_GetValue(&hadc1);
	HAL_ADC_Stop(&hadc1);

	/* Conversione ADC → tensione */
	voltage = ((float)adc_in2 * 3.3f) / 4095.0f;

	/* LM35: 10 mV per °C */
	temperature_c = (voltage * 100.0f) + 10;

	/* Task Termination */
	Os_TerminateTask();
}

TASK(OLED_Task)
{
#ifdef USB_LOGGING
	printf("Task OLED_Task running...\r\n");
#endif

	/* TODO: User code */

	ssd1306_set_cursor(&oled, 0, 48);
	ssd1306_write_string(&oled, "OLED TASK RUNNING...", 1);
    ssd1306_update(&oled);

	/* Task Termination */
	Os_TerminateTask();
}

TASK(Serial_Task)
{
#ifdef USB_LOGGING
	printf("Task OLED_Task running...\r\n");
#endif

	/* TODO: User code */
	uart3_send_string("Serial Hello World!!!\r\n");

	/* Task Termination */
	Os_TerminateTask();
}
